[workspace]
resolver = "2"
members = [
  "Build/crates/honzo-core",
  "Build/crates/honzo-chunks",
  "Build/crates/honzo-io",
  "Build/crates/honzo-fixtures",
  "Build/crates/honzo-convert",
  "Build/crates/honzo-c",
  "Build/crates/honzo-wasm",
  "Build/crates/honzo-cli",
  "Tests",
]

[workspace.package]
version = "0.1.3"
edition = "2021"
license = "Apache-2.0"
documentation = "https://nisoku.org/Honzo"
