meta:
  id: honzo
  title: Honzo Ebook Format
  file-extension: hzo
  endian: le
  license: Apache-2.0

doc: |
  Honzo (本理想, .hzo): A modern, opinionated ebook format.
  
  Design principles:
  - HEAD contains all chunk sizes (single source of truth)
  - TOC describes all DATA subchunks (offsets relative to DATA start)
  - DATA is a dumb payload blob - no self-description needed
  - EXTRA holds optional namespaced extensions (org.nisoku.*)
  - META holds MessagePack-encoded metadata
  
  Magic: "HONO" (0x484F4E4F)
  
  Chunk types (4-byte ASCII tags):
    CHAP  - Chapter content (markup_type swappable per chunk)
    IMG_  - Image
    CSS_  - Stylesheet
    FONT  - Font file
    COVR  - Cover image (always first TOC entry)
    COVT  - Cover thumbnail (auto-generated by libhonzo if absent)
    NOTE  - Endnotes / collected reference section
    SIDX  - Search index (inverted: term -> [(chunk_id, offset)])
    MATH  - Math content (MathML or equiv)
  
  Compression (per-chunk, flag in TOC entry):
    0 = none
    1 = zlib
    2 = zstd
  
  Markup types (for CHAP chunks):
    0 = HMD (Honzo Markdown, default)
    1 = HTML (fallback)
  
  Layout modes (in META):
    0 = reflowable  (novels, non-fiction)
    1 = fixed       (picture books, textbooks)
    2 = scroll      (webtoons, manhwa, manga)
  
  EXTRA namespacing: org.nisoku.*
    org.nisoku.anno  - portable annotations/highlights/bookmarks
    org.nisoku.drm   - AES-256 content encryption + key envelope
    org.nisoku.sync  - read-aloud audio sync / narration timing
  
  Byte order: little-endian throughout.

seq:
  - id: magic
    contents: [0x48, 0x4F, 0x4E, 0x4F]  # "HONO"
    doc: Magic number identifier

  - id: head
    type: honzo_head
    doc: Fixed binary header, 48 bytes. Single source of truth for chunk sizes.

  - id: toc
    type: toc_chunk
    size: head.toc_size
    doc: |
      Table of contents. Describes every subchunk inside DATA:
      type, ID, offset (relative to DATA start), size, compression,
      markup type, CRC32 (CHAP only), alt text (IMG_ only),
      font license (FONT only). Also contains the page map (PMAP).

  - id: data
    type: data_chunk
    size: head.data_size
    doc: |
      Raw payload blob. Dumb by design - all structure lives in TOC.
      Contains: CHAP, IMG_, CSS_, FONT, COVR, COVT, NOTE, SIDX, MATH chunks.

  - id: extra
    type: extra_chunk
    size: head.extra_size
    if: head.extra_size > 0
    doc: |
      Optional namespaced extensions under org.nisoku.*
      Each entry: [tag: 4 bytes][length: 4 bytes][body: length bytes]

  - id: meta
    size: head.meta_size
    if: head.meta_size > 0
    doc: |
      MessagePack-encoded HonzoMetadata. See META SCHEMA below.
      
      TOP-LEVEL FIELDS:
      
      IDENTITY:
        title           map<lang, string>   localized title (e.g. {"en": "..."})
        subtitle        map<lang, string>   optional
        description     map<lang, string>   optional, localized blurb
        original_title  string              optional, for translations
        original_lang   string              BCP 47, optional
        original_authors [string]           optional
      
      PEOPLE:
        authors         [string]            display order, required
        contributors    [{name, role}]      role enum: translator, editor,
                                            illustrator, narrator, cover_artist,
                                            colorist, custom
        publisher       string
        imprint         string              optional
      
      CLASSIFICATION:
        genres          [string]            human-readable, highly recommended
        tags            [string]            optional
        bisac           [string]            machine-readable BISAC codes
        language        string              BCP 47, required
        direction       string              "ltr" | "rtl" | "ttb"
        rating          string              "all"|"teen"|"mature"|"explicit"
        content_warnings [string]           e.g. ["violence", "flashing_lights"]
      
      SERIES:
        series {
          title         string              required if series present
          position      string              e.g. "3/10"
          arc           string              optional
        }
      
      PUBLICATION:
        identifiers     [{type, value}]     type: "isbn"|"doi"|"uuid"|"asin"|...
                                            uuid auto-generated by libhonzo
        isbn_status     string              "assigned"|"pending"|"none"
        date_published  string              ISO 8601
        date_ebook_pub  string              ISO 8601
        edition         string
        license         string              SPDX id or freeform
        revisions       [{version, date, note}]  semver history
                                            HEAD stores current version string
      
      LAYOUT & RENDERING:
        layout          uint8               0=reflowable, 1=fixed, 2=scroll
        spread_behavior string              "auto"|"single"|"double_left"|
                                            "double_right"|"double_cover"
        hints {
          typography    string              "serif"|"sans"|"monospace"|"any"
          hyphenation   bool
          widow_orphan  bool
          night_mode_inversion bool
          justify       bool
        }
      
      READER STATS:
        word_count          uint
        reading_time_mins   uint            auto-computed by libhonzo
      
      ACCESSIBILITY:
        accessibility {
          alt_text        bool              all images have alt text
          reading_order   bool              logical reading order guaranteed
          screen_reader   bool              tested with screen reader
          dyslexia_friendly bool
          wcag_level      string            "A"|"AA"|"AAA"|null
        }
      
      LIBRARY / ARCHIVAL:
        sort_title      string              e.g. "Great Gatsby, The"
        sort_author     string              e.g. "Le Guin, Ursula K."
        source_url      string              optional, provenance
        source_format   string              "epub3"|"scan"|etc, optional
        digitized_by    string              optional
        production_notes string            optional, editorial decisions
      
      ORIGINAL WORK (translations):
        original_title  string
        original_lang   string              BCP 47
        original_authors [string]

types:
  honzo_head:
    seq:
      - id: version_major
        type: u1
        doc: Format major version (currently 1)

      - id: version_minor
        type: u1
        doc: Format minor version (currently 0)

      - id: min_reader_version
        type: u2
        doc: |
          Minimum libhonzo version required to read this file.
          Readers below this version should refuse to open the file
          rather than silently misparse it.

      - id: flags
        type: u4
        doc: |
          Bit flags (u32 for future-proofing):
          Bits 0-1: Default compression (0=none, 1=zlib, 2=zstd)
          Bits 2-3: Layout mode (0=reflowable, 1=fixed, 2=scroll)
          Bit  4:   DRM present (0=no, 1=yes, see org.nisoku.drm in EXTRA)
          Bit  5:   Has search index (SIDX chunk present in DATA)
          Bit  6:   Has annotations (org.nisoku.anno in EXTRA)
          Bit  7:   Has audio sync (org.nisoku.sync in EXTRA)
          Bits 8-31: Reserved, must be 0

      - id: chunk_count
        type: u4
        doc: Total number of subchunks in DATA

      - id: toc_size
        type: u8
        doc: Size of TOC chunk in bytes

      - id: data_size
        type: u8
        doc: Size of DATA chunk in bytes

      - id: extra_size
        type: u8
        doc: Size of EXTRA chunk in bytes (0 if absent)

      - id: meta_size
        type: u8
        doc: Size of META chunk in bytes

      - id: reserved
        size: 4
        doc: Must be zero

    instances:
      compression_default:
        value: flags & 0x03
        doc: Default compression mode (0=none, 1=zlib, 2=zstd)

      layout_mode:
        value: (flags >> 2) & 0x03
        doc: Layout mode (0=reflowable, 1=fixed, 2=scroll)

      has_drm:
        value: (flags & 0x10) != 0
        doc: True if DRM is present

      has_sidx:
        value: (flags & 0x20) != 0
        doc: True if a SIDX search index chunk is present in DATA

      has_anno:
        value: (flags & 0x40) != 0
        doc: True if org.nisoku.anno is present in EXTRA

      has_sync:
        value: (flags & 0x80) != 0
        doc: True if org.nisoku.sync is present in EXTRA


  toc_chunk:
    seq:
      - id: num_entries
        type: u4
        doc: Number of DATA subchunk entries

      - id: entries
        type: toc_entry
        repeat: expr
        repeat-expr: num_entries
        doc: One entry per DATA subchunk, in reading/storage order

      - id: num_pmap_entries
        type: u4
        doc: Number of page map entries (0 if no print page map)

      - id: pmap
        type: pmap_entry
        repeat: expr
        repeat-expr: num_pmap_entries
        doc: |
          Optional print page map. Maps logical print page numbers
          to a chunk ID + byte offset within that chunk.
          Useful for academic citations ("see page 42").

  toc_entry:
    seq:
      - id: chunk_type
        type: str
        size: 4
        encoding: ASCII
        doc: |
          4-byte ASCII type tag:
          CHAP, IMG_, CSS_, FONT, COVR, COVT, NOTE, SIDX, MATH

      - id: chunk_id
        type: u4
        doc: Unique chunk identifier (u32 for future-proofing)

      - id: offset
        type: u8
        doc: Byte offset from start of DATA chunk (relative, not absolute)

      - id: size_compressed
        type: u4
        doc: Size of chunk data in bytes (compressed, or raw if compression=0)

      - id: size_raw
        type: u4
        doc: Uncompressed size in bytes (== size_compressed if no compression)

      - id: compression
        type: u1
        doc: Compression method (0=none, 1=zlib, 2=zstd)

      - id: markup_type
        type: u1
        doc: |
          Markup/content type. Meaningful for CHAP chunks:
          0 = HMD (Honzo Markdown)
          1 = HTML
          For all other chunk types: 0

      - id: cover_type
        type: u1
        doc: |
          Cover variant. Meaningful for COVR chunks:
          0 = front
          1 = back
          2 = full_spread
          For all other chunk types: 0

      - id: flags
        type: u1
        doc: |
          Per-entry flags:
          Bit 0: encrypted (DRM applies to this chunk)
          Bits 1-7: reserved

      - id: crc32
        type: u4
        doc: |
          CRC32 of the raw (uncompressed) chunk data.
          Meaningful for CHAP chunks - use to detect partial corruption.
          Set to 0 for all other chunk types.

      - id: alt_text_len
        type: u2
        doc: |
          Length of alt_text string in bytes.
          Meaningful for IMG_ chunks. 0 = no alt text.

      - id: alt_text
        type: str
        size: alt_text_len
        encoding: UTF-8
        if: alt_text_len > 0
        doc: Accessibility alt text for images. Also useful for secret messages.

      - id: font_embedding
        type: u1
        if: chunk_type == "FONT"
        doc: |
          Font embedding permission:
          0 = allowed
          1 = print_only
          2 = no_modify
          3 = no_embed

      - id: font_license_url_len
        type: u2
        if: chunk_type == "FONT"
        doc: Length of font license URL string in bytes. 0 = none.

      - id: font_license_url
        type: str
        size: font_license_url_len
        encoding: UTF-8
        if: chunk_type == "FONT" and font_license_url_len > 0
        doc: URL pointing to the font's license

    instances:
      is_encrypted:
        value: (flags & 0x01) != 0
        doc: True if this chunk is DRM-encrypted

  pmap_entry:
    seq:
      - id: print_page
        type: u4
        doc: Logical print page number (1-based)

      - id: chunk_id
        type: u4
        doc: ID of the CHAP chunk containing this page

      - id: byte_offset
        type: u4
        doc: Byte offset within the (decompressed) chunk where the page begins


  data_chunk:
    seq:
      - id: raw
        size-eos: true
        doc: |
          Raw concatenated chunk payloads.
          Use TOC entries to seek to individual chunks by offset + size.
          DATA itself is intentionally dumb - all structure is in TOC.
          
          Chunk payload formats by type:
          
          CHAP / NOTE:
            Raw markup bytes (HMD or HTML per toc_entry.markup_type).
            Footnotes are named anchors within the chunk.
            Endnote chunks (NOTE) are typed differently so renderers
            treat them as reference sections, not linear reading content.
          
          IMG_:
            Raw image bytes (JPEG, PNG, WebP, etc).
            Format inferred from magic bytes by the reader.
          
          CSS_:
            Raw UTF-8 CSS bytes.
          
          FONT:
            Raw font bytes (OTF, TTF, WOFF2, etc).
            Format inferred from magic bytes by the reader.
          
          COVR / COVT:
            Raw image bytes. COVT auto-generated by libhonzo if absent.
            cover_type in TOC entry: 0=front, 1=back, 2=full_spread.
          
          SIDX (search index):
            MessagePack-encoded inverted index.
            Structure: { term: [[chunk_id, byte_offset], ...], ... }
            Built at creation time by libhonzo, never on-device.
          
          MATH:
            MathML or equivalent math markup, UTF-8 encoded.


  extra_chunk:
    seq:
      - id: entries
        type: extra_entry
        repeat: eos
        doc: Zero or more namespaced extension entries

  extra_entry:
    seq:
      - id: tag
        type: str
        size: 4
        encoding: ASCII
        doc: |
          4-byte tag identifying the extension namespace.
          Official org.nisoku extensions use tags:
            ANNO = org.nisoku.anno  (portable annotations)
            DRM_ = org.nisoku.drm   (AES-256 encryption envelope)
            SYNC = org.nisoku.sync  (read-aloud audio sync)

      - id: namespace_len
        type: u2
        doc: Length of full namespace string (e.g. "org.nisoku.anno")

      - id: namespace
        type: str
        size: namespace_len
        encoding: UTF-8
        doc: Full reverse-domain namespace string

      - id: body_len
        type: u4
        doc: Length of extension body in bytes

      - id: body
        size: body_len
        doc: |
          Extension payload. Format defined per namespace:
          
          org.nisoku.anno:
            MessagePack array of annotation objects:
            [{chunk_id, offset, length, type, note?, color?, created_at}, ...]
            type: "highlight" | "bookmark" | "note"
            Stored IN the file - portable across all readers.
          
          org.nisoku.drm:
            MessagePack object:
            {
              scheme: "aes256-cbc",
              encrypted_chunks: [chunk_id, ...],
              key_envelope: bytes,    // symmetric key encrypted with platform key
              license_url: string?,
              expires_at: string?     // ISO 8601
            }
            Encrypted chunks have is_encrypted=true in their TOC entry.
          
          org.nisoku.sync:
            MessagePack array of sync cue objects:
            [{chunk_id, offset, audio_timestamp_ms}, ...]
            Maps text positions to narration audio timestamps.

enums:
  compression_type:
    0: none
    1: zlib
    2: zstd

  layout_mode:
    0: reflowable
    1: fixed
    2: scroll

  cover_type:
    0: front
    1: back
    2: full_spread

  font_embedding:
    0: allowed
    1: print_only
    2: no_modify
    3: no_embed

  markup_type:
    0: hmd
    1: html
