[package]
name = "honzo-tests"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
honzo-c = { path = "../Build/crates/honzo-c" }
honzo-core = { path = "../Build/crates/honzo-core" }
honzo-convert = { path = "../Build/crates/honzo-convert" }
honzo-chunks = { path = "../Build/crates/honzo-chunks" }
honzo-io = { path = "../Build/crates/honzo-io" }
rmp-serde = "1"
serde = { version = "1", features = ["derive"] }
lopdf = "0.40.0"
image = { version = "0.25", default-features = false, features = ["jpeg"] }
