[package]
name = "honzo-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Integration tests for the Honzo ebook format"
publish = false

[dependencies]
honzo-c = { path = "../Build/crates/honzo-c", version = "0.1" }
honzo-core = { path = "../Build/crates/honzo-core", version = "0.1" }
honzo-convert = { path = "../Build/crates/honzo-convert", version = "0.1" }
honzo-chunks = { path = "../Build/crates/honzo-chunks", version = "0.1" }
honzo-io = { path = "../Build/crates/honzo-io", version = "0.1" }
rmp-serde = "1.3.1"
serde = { version = "1.0.228", features = ["derive"] }
lopdf = "0.43.0"
image = { version = "0.25.10", default-features = false, features = ["jpeg"] }
diplomat-runtime = "0.15.1"
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }
quick-xml = "0.41.0"
x25519-dalek = { version = "2", default-features = false, features = ["static_secrets", "getrandom"] }
