[package]
name = "libhonzo"
version = "0.1.1"
authors = ["NellowTCS"]
license = "Apache-2.0"
description = "Fast and streaming EPUB parser library"

[library]
name = "libhonzo"
crate-type = ["cdylib", "rlib"]
features = ["c-ffi"]

[dependencies]

[output]
