/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_honzowasm_free: (a: number, b: number) => void;
export const honzo_build: (a: any) => [number, number, number, number];
export const honzowasm_chunk_count: (a: number) => number;
export const honzowasm_get_chunk: (a: number, b: number) => [number, number, number, number];
export const honzowasm_get_meta: (a: number) => [number, number, number, number];
export const honzowasm_get_meta_parsed: (a: number) => [number, number, number];
export const honzowasm_get_toc: (a: number) => [number, number, number];
export const honzowasm_has_drm: (a: number) => number;
export const honzowasm_has_sidx: (a: number) => number;
export const honzowasm_layout_mode: (a: number) => number;
export const honzowasm_new: (a: number, b: number, c: number) => [number, number, number];
export const rust_zstd_wasm_shim_calloc: (a: number, b: number) => number;
export const rust_zstd_wasm_shim_free: (a: number) => void;
export const rust_zstd_wasm_shim_malloc: (a: number) => number;
export const rust_zstd_wasm_shim_memcmp: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memcpy: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memmove: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memset: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_qsort: (a: number, b: number, c: number, d: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
